### ISSUE TITLE
Sidebar button crashes browser

### ISSUE THREAD

**Issue by harperaa** [joshkent94/BrowseGPT#56]
Hi, I am using Brave, have installed code, set .env vars, and ran with turbo dev.  Installed extension, clicked icon, logged into google (have Google OAUTH info in .env).  Then, I see the sidebar button highlighted, if I click it, the browser crashes.  There are no errors or logs of the event.  I tried opening the service workers logs, again, nothing, they crash too.  Please advise how to get running on virgin install.  Something seems to be missing in instructions, I am wondering if there is an install step missing.  Looks promising, would like to try it and extend it, but can't get off the ground.  I am happy to connect and share screens to troubleshoot. Thanks.

**Comment by joshkent94** [comment]
Hey! Glad to hear to you want to get involved. Are you ok sending me your email address? I can add you to a Slack channel so we can share screenshots etc.
